version: '3'

services:
  db:
    image: postgres:15.2
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "user-register-db"